# Generated by Django 5.2 on 2025-05-10 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='warden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hostels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='available_rooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='price_per_month',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='total_rooms',
            field=models.PositiveIntegerField(),
        ),
    ]
