# Generated by Django 5.2 on 2025-05-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_visitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
